// GENERATED by tools/gen_controls.py from firmware/controls.json.
// Do not edit; edit the JSON and regenerate. Drift fails preflight.
#pragma once

#include <cstdint>

#include "ui_state.h"

namespace core {

enum class ControlKind : uint8_t { Toggle, Level, Choice, Picker, Stepper, Color, Action, Link, Readout };
enum class Fmt : uint8_t { Plain, Pct254, Pct255, Db10 };
enum class Bind : uint8_t {
    None, HomeRooms, HomeStrip, HomeYamaha, HomeTeufel, HomeDisco,
    HomeFog, HomeClimate, RoomOn, RoomBri, LwOn, LwBri,
    LwEffect, YamOn, YamVol, YamInput, YamMute, TfOn,
    TfPath, TfVol, TfInput, TfMute, DiscoOn, DiscoMode,
    FogOn, FogTank, FogNote, ClimaIn, ClimaOut, ClimaWx,
    ClimaWxDesc, ClimaPi,
};

struct ControlSpec {
    ControlKind kind;
    Bind bind;
    const char* label;
    int min, max, step;
    Fmt fmt;
    char key;          // accelerator letter, 0 for none
};

constexpr int kSpecCount_Home = 7;
constexpr ControlSpec kSpec_Home[] = {
    {ControlKind::Link, Bind::HomeRooms, "1 Raeume", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Link, Bind::HomeStrip, "2 Strip", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Link, Bind::HomeYamaha, "3 Yamaha", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Link, Bind::HomeTeufel, "4 Teufel", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Link, Bind::HomeDisco, "5 Disco", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Link, Bind::HomeFog, "6 Nebel", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Link, Bind::HomeClimate, "7 Klima", 0, 0, 1, Fmt::Plain, 0},
};

constexpr int kSpecCount_Rooms = 0;
constexpr const ControlSpec* kSpec_Rooms = nullptr;

constexpr int kSpecCount_Room = 2;
constexpr ControlSpec kSpec_Room[] = {
    {ControlKind::Toggle, Bind::RoomOn, "An", 0, 0, 1, Fmt::Plain, 'p'},
    {ControlKind::Level, Bind::RoomBri, "Helligkeit", 1, 254, 30, Fmt::Pct254, 0},
};

constexpr int kSpecCount_Lichtwerk = 3;
constexpr ControlSpec kSpec_Lichtwerk[] = {
    {ControlKind::Toggle, Bind::LwOn, "Strom", 0, 0, 1, Fmt::Plain, 'p'},
    {ControlKind::Level, Bind::LwBri, "Helligkeit", 0, 255, 32, Fmt::Pct255, 0},
    {ControlKind::Choice, Bind::LwEffect, "Effekt", 0, 0, 1, Fmt::Plain, 'e'},
};

constexpr int kSpecCount_Yamaha = 4;
constexpr ControlSpec kSpec_Yamaha[] = {
    {ControlKind::Toggle, Bind::YamOn, "Strom", 0, 0, 1, Fmt::Plain, 'p'},
    {ControlKind::Level, Bind::YamVol, "Pegel", -800, -200, 10, Fmt::Db10, 0},
    {ControlKind::Choice, Bind::YamInput, "Eingang", 0, 0, 1, Fmt::Plain, 'i'},
    {ControlKind::Toggle, Bind::YamMute, "Stumm", 0, 0, 1, Fmt::Plain, 'm'},
};

constexpr int kSpecCount_Teufel = 5;
constexpr ControlSpec kSpec_Teufel[] = {
    {ControlKind::Toggle, Bind::TfOn, "Strom ~", 0, 0, 1, Fmt::Plain, 'p'},
    {ControlKind::Choice, Bind::TfPath, "Weg", 0, 0, 1, Fmt::Plain, 'w'},
    {ControlKind::Level, Bind::TfVol, "Lautst. ~", 0, 50, 1, Fmt::Plain, 0},
    {ControlKind::Choice, Bind::TfInput, "Eingang ~", 0, 0, 1, Fmt::Plain, 'i'},
    {ControlKind::Toggle, Bind::TfMute, "Stumm ~", 0, 0, 1, Fmt::Plain, 'm'},
};

constexpr int kSpecCount_Disco = 2;
constexpr ControlSpec kSpec_Disco[] = {
    {ControlKind::Toggle, Bind::DiscoOn, "Lichter", 0, 0, 1, Fmt::Plain, 'p'},
    {ControlKind::Choice, Bind::DiscoMode, "Modus", 0, 0, 1, Fmt::Plain, 'o'},
};

constexpr int kSpecCount_Fog = 3;
constexpr ControlSpec kSpec_Fog[] = {
    {ControlKind::Toggle, Bind::FogOn, "Nebel", 0, 0, 1, Fmt::Plain, 'p'},
    {ControlKind::Readout, Bind::FogTank, "Tank", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Readout, Bind::FogNote, "220 V, heiss", 0, 0, 1, Fmt::Plain, 0},
};

constexpr int kSpecCount_Climate = 5;
constexpr ControlSpec kSpec_Climate[] = {
    {ControlKind::Readout, Bind::ClimaIn, "Innen", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Readout, Bind::ClimaOut, "Garten", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Readout, Bind::ClimaWx, "Wetter", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Readout, Bind::ClimaWxDesc, "", 0, 0, 1, Fmt::Plain, 0},
    {ControlKind::Readout, Bind::ClimaPi, "Pi", 0, 0, 1, Fmt::Plain, 0},
};

inline const ControlSpec* specsFor(Screen s, int& count) {
    switch (s) {
        case Screen::Home: count = kSpecCount_Home; return kSpec_Home;
        case Screen::Rooms: count = kSpecCount_Rooms; return kSpec_Rooms;
        case Screen::Room: count = kSpecCount_Room; return kSpec_Room;
        case Screen::Lichtwerk: count = kSpecCount_Lichtwerk; return kSpec_Lichtwerk;
        case Screen::Yamaha: count = kSpecCount_Yamaha; return kSpec_Yamaha;
        case Screen::Teufel: count = kSpecCount_Teufel; return kSpec_Teufel;
        case Screen::Disco: count = kSpecCount_Disco; return kSpec_Disco;
        case Screen::Fog: count = kSpecCount_Fog; return kSpec_Fog;
        case Screen::Climate: count = kSpecCount_Climate; return kSpec_Climate;
        default: count = 0; return nullptr;
    }
}

}  // namespace core
