// GENERATED by tools/gen_ir_table.py — do not edit by hand.
//
// Source: vendor/teufel-ir-mapping.csv (sha256/16 = 9afd169abb99b2a6)
// which is a verbatim copy of the house-canonical table used by
// powerhifi-controller. Regenerate instead of editing:
//     python3 tools/gen_ir_table.py
//
// Protocol: NEC, 38 kHz carrier, 16-bit address 0x5780.
//
// Known quirk: MUTE (0x28) reaches the box and does nothing while POWER and
// VOLUME work. The byte is mislabelled in the original capture. Documented,
// unexplained, and not a fault of this firmware.
#pragma once
#include <cstdint>
#include <cstddef>

namespace ir {

constexpr uint16_t kTeufelAddress = 0x5780;
constexpr char kTeufelSourceDigest[] = "9afd169abb99b2a6";

enum TeufelCommand : uint8_t {
    IR_POWER = 0x48,
    IR_BLUETOOTH = 0x40,
    IR_MUTE = 0x28,
    IR_VOL_UP = 0xB0,
    IR_VOL_DOWN = 0x30,
    IR_LEFT = 0x78,
    IR_RIGHT = 0xF8,
    IR_BASS_UP = 0x58,
    IR_BASS_DOWN = 0x41,
    IR_MID_UP = 0x68,
    IR_MID_DOWN = 0x42,
    IR_TREBLE_UP = 0xB8,
    IR_TREBLE_DOWN = 0x43,
    IR_AUX = 0x44,
    IR_LINE = 0x45,
    IR_OPT = 0x3F,
    IR_USB = 0xDF,
    IR_BAL_LEFT = 0xBF,
    IR_BAL_RIGHT = 0x5F,
};

struct TeufelEntry {
    const char* name;      // lower-case, as typed on the command line
    uint8_t code;
};

constexpr TeufelEntry kTeufelCommands[] = {
    {"power", 0x48},
    {"bluetooth", 0x40},
    {"mute", 0x28},
    {"vol_up", 0xB0},
    {"vol_down", 0x30},
    {"left", 0x78},
    {"right", 0xF8},
    {"bass_up", 0x58},
    {"bass_down", 0x41},
    {"mid_up", 0x68},
    {"mid_down", 0x42},
    {"treble_up", 0xB8},
    {"treble_down", 0x43},
    {"aux", 0x44},
    {"line", 0x45},
    {"opt", 0x3F},
    {"usb", 0xDF},
    {"bal_left", 0xBF},
    {"bal_right", 0x5F},
};

constexpr size_t kTeufelCommandCount =
    sizeof(kTeufelCommands) / sizeof(kTeufelCommands[0]);

}  // namespace ir
