#!/usr/bin/env python3
"""Generate the control tables from firmware/controls.json.

Writes firmware/lib/core/controls_table.h and docs/CONTROLS.md. Both are
committed; `--check` exits non-zero when either differs from what the JSON
would produce — the same discipline as the IR table, for the same reason: a
hand-edited copy drifts silently.

Usage:  python3 tools/gen_controls.py          # write both
        python3 tools/gen_controls.py --check  # verify, write nothing
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
JSON = ROOT / "firmware" / "controls.json"
HEADER = ROOT / "firmware" / "lib" / "core" / "controls_table.h"
DOC = ROOT / "docs" / "CONTROLS.md"

# Screens that are not control lists and therefore have no table.
NON_LIST_SCREENS = ("Console", "Diagnostics")

KIND_WORD = {
    "Toggle": "an/aus", "Level": "Regler", "Choice": "Auswahl (sendet sofort)",
    "Picker": "Auswahl (Enter sendet)", "Stepper": "Schritt -/+", "Color": "Farbe",
    "Action": "Aktion", "Link": "oeffnet", "Readout": "Anzeige",
}


def load():
    return json.loads(JSON.read_text())


def _cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_header(table):
    kinds = table["kinds"]
    fmts = table["fmts"]
    binds = ["None"] + [c["bind"] for controls in table["screens"].values() for c in controls]
    out = []
    out.append("// GENERATED by tools/gen_controls.py from firmware/controls.json.")
    out.append("// Do not edit; edit the JSON and regenerate. Drift fails preflight.")
    out.append("#pragma once")
    out.append("")
    out.append("#include <cstdint>")
    out.append("")
    out.append('#include "ui_state.h"')
    out.append("")
    out.append("namespace core {")
    out.append("")
    out.append("enum class ControlKind : uint8_t { " + ", ".join(kinds) + " };")
    out.append("enum class Fmt : uint8_t { " + ", ".join(fmts) + " };")
    out.append("enum class Bind : uint8_t {")
    for i in range(0, len(binds), 6):
        out.append("    " + ", ".join(binds[i:i + 6]) + ",")
    out.append("};")
    out.append("")
    out.append("struct ControlSpec {")
    out.append("    ControlKind kind;")
    out.append("    Bind bind;")
    out.append("    const char* label;")
    out.append("    int min, max, step;")
    out.append("    Fmt fmt;")
    out.append("    char key;          // accelerator letter, 0 for none")
    out.append("};")
    out.append("")
    for screen, controls in table["screens"].items():
        out.append(f"constexpr int kSpecCount_{screen} = {len(controls)};")
        if not controls:
            out.append(f"constexpr const ControlSpec* kSpec_{screen} = nullptr;")
            out.append("")
            continue
        out.append(f"constexpr ControlSpec kSpec_{screen}[] = {{")
        for c in controls:
            key = f"'{c['key']}'" if c.get("key") else "0"
            out.append("    {ControlKind::%s, Bind::%s, %s, %d, %d, %d, Fmt::%s, %s}," % (
                c["kind"], c["bind"], _cstr(c["label"]),
                c.get("min", 0), c.get("max", 0), c.get("step", 1),
                c.get("fmt", "Plain"), key))
        out.append("};")
        out.append("")
    out.append("inline const ControlSpec* specsFor(Screen s, int& count) {")
    out.append("    switch (s) {")
    for screen in table["screens"]:
        out.append(f"        case Screen::{screen}: count = kSpecCount_{screen}; return kSpec_{screen};")
    out.append("        default: count = 0; return nullptr;")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("}  // namespace core")
    return "\n".join(out) + "\n"


def _range_text(c):
    if c["kind"] != "Level":
        return ""
    fmt = c.get("fmt", "Plain")
    lo, hi, st = c["min"], c["max"], c["step"]
    if fmt == "Db10":
        return f"{lo / 10:.1f} … {hi / 10:.1f} dB, Schritt {st / 10:g} dB"
    if fmt in ("Pct254", "Pct255"):
        return f"{lo} … {hi} (als %), Schritt {st}"
    return f"{lo} … {hi}, Schritt {st}"


def render_doc(table):
    out = ["# Controls", "",
           "*Generated from `firmware/controls.json` by `tools/gen_controls.py`; do not edit.*",
           "",
           "Every app screen is a list of controls. `;` `.` move the cursor, `,` `/` "
           "(or `-` `+`) adjust the selected control, `Enter` flips a toggle, opens a "
           "link or fires an action, `Space` flips the screen's primary toggle. "
           "Readouts are skipped by the cursor. See the design spec for the grammar.",
           ""]
    for screen, controls in table["screens"].items():
        out.append(f"## {screen}")
        out.append("")
        if not controls:
            out.append("*Built from the snapshot at runtime (one row per room).*")
            out.append("")
            continue
        out.append("| Control | Kind | Range | Key |")
        out.append("|---|---|---|---|")
        for c in controls:
            label = c["label"] or "—"
            out.append(f"| `{label}` | {KIND_WORD[c['kind']]} | {_range_text(c)} | "
                       f"{'`' + c['key'] + '`' if c.get('key') else ''} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv):
    table = load()
    header = render_header(table)
    doc = render_doc(table)
    if "--check" in argv:
        bad = []
        if not HEADER.exists() or HEADER.read_text() != header:
            bad.append(str(HEADER.relative_to(ROOT)))
        if not DOC.exists() or DOC.read_text() != doc:
            bad.append(str(DOC.relative_to(ROOT)))
        if bad:
            print("controls table drifted: " + ", ".join(bad) +
                  " — run python3 tools/gen_controls.py")
            return 1
        print("controls table is current")
        return 0
    HEADER.write_text(header)
    DOC.write_text(doc)
    n = sum(len(v) for v in table["screens"].values())
    print(f"{HEADER.relative_to(ROOT)}: {n} controls on {len(table['screens'])} screens")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
