#!/usr/bin/env python3
"""Generate firmware/lib/core/ir_teufel.h from the canonical IR mapping CSV.

Run after changing vendor/teufel-ir-mapping.csv:

    python3 tools/gen_ir_table.py

The header carries a checksum of its input; tests/test_ir_table.py fails if
the two drift apart, so a stale table cannot ship unnoticed.
"""

import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSV = ROOT / "vendor" / "teufel-ir-mapping.csv"
OUT = ROOT / "firmware" / "lib" / "core" / "ir_teufel.h"

TEUFEL_ADDR = 0x5780        # verified in teufel-power-hifi-ir-rx-ts.ino


def parse(text: str):
    rows = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        code, _, name = line.partition(";")
        if not name:
            raise SystemExit(f"malformed row: {line!r}")
        rows.append((name.strip(), int(code, 16)))
    if not rows:
        raise SystemExit("empty mapping")
    return rows


def csum(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def render(rows, digest: str) -> str:
    entries = "\n".join(
        f'    {{"{name.lower()}", 0x{code:02X}}},' for name, code in rows)
    names = "\n".join(f"    IR_{name.upper()} = 0x{code:02X}," for name, code in rows)
    return f"""// GENERATED by tools/gen_ir_table.py — do not edit by hand.
//
// Source: vendor/teufel-ir-mapping.csv (sha256/16 = {digest})
// which is a verbatim copy of the house-canonical table used by
// powerhifi-controller. Regenerate instead of editing:
//     python3 tools/gen_ir_table.py
//
// Protocol: NEC, 38 kHz carrier, 16-bit address 0x{TEUFEL_ADDR:04X}.
//
// Known quirk: MUTE (0x28) reaches the box and does nothing while POWER and
// VOLUME work. The byte is mislabelled in the original capture. Documented,
// unexplained, and not a fault of this firmware.
#pragma once
#include <cstdint>
#include <cstddef>

namespace ir {{

constexpr uint16_t kTeufelAddress = 0x{TEUFEL_ADDR:04X};
constexpr char kTeufelSourceDigest[] = "{digest}";

enum TeufelCommand : uint8_t {{
{names}
}};

struct TeufelEntry {{
    const char* name;      // lower-case, as typed on the command line
    uint8_t code;
}};

constexpr TeufelEntry kTeufelCommands[] = {{
{entries}
}};

constexpr size_t kTeufelCommandCount =
    sizeof(kTeufelCommands) / sizeof(kTeufelCommands[0]);

}}  // namespace ir
"""


def main():
    text = CSV.read_text()
    rows = parse(text)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(rows, csum(text)))
    print(f"{OUT.relative_to(ROOT)}: {len(rows)} commands, digest {csum(text)}")


if __name__ == "__main__":
    sys.exit(main())
